### ISSUE TITLE
Allow end users to download the video to their device 

### ISSUE THREAD

**Issue by jai-dewani** [utkarsh-raj/umusic#25]
I saw this blog post of how to make a file serving server and it struck me that we can add some file serving routes and host the application. Whenever a person clicks on download the file will get downloaded on the server but the user will also get a link to access that file which will go through the file serving routes with the help of which he should be able to download the file to his device. 

Kinda hacky but is a good place to start with

**Comment by utkarsh-raj** [comment]
Sounds great! I was trying to make such functionality in the very initial days of the project.

Since I was deploying it on c9 there was a limit of how much data I can store on the server before serving it to the client. If we can try making a socket connection through the server so that the data immediately goes to the client, maybe we can bypass the storage problems.

**Comment by jai-dewani** [comment]
Yeah, that is an elegant solution, another way is to download a video on the server and delete it the next day via some automated script to avoid storage problems :p

I am saying this because I don't have a clear idea about socket right now (it has been years :stuck_out_tongue_closed_eyes: ) I'll try searching for some blog or tutorial on how to use sockets to forward data streams.
